/* tslint:disable */
/* eslint-disable */
/**
 * ride-service API
 * OpenAPI contract for the ride-service (create/match/accept/start/complete rides + health)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

